apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: mkdspace
  labels:
    app: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: axionacr2.azurecr.io/ingestion-service:v1
        ports:
        - containerPort: 8000
