apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: digitalopsdev
spec:
  type: LoadBalancer          
  selector:
    app: ui                 
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 80        
