apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata_name }}
  labels:
    app: {{ .Values.metadata_label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata_label }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          # --- CONDITIONAL IF/ELSE RESOURCE ALLOCATION ---
          {{- if eq .Values.envName "production" }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          {{- else }}
          resources: {}
          {{- end }}
          # ------------------------------------------------
          env:
            - name: APPLICATION_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.metadata_name }}-config
                  key: APP_ENV
            - name: DB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.metadata_name }}-config
                  key: DATABASE_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metadata_name }}-secret
                  key: DATABASE_PASSWORD
