apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.metadata_name }}-secret
  labels:
    app: {{ .Values.metadata_label }}
data:
  DATABASE_PASSWORD: {{ .Values.db_password | b64enc }}
