apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: mkdspace
  labels:
    app: pgadmin
spec:
  
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@mukeshdani.online"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "mkdani@123"