apiVersion: v1
kind: Pod
metadata:
  name: affinitypod
spec:
  containers:
  - name: nginx 
    image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "mukesh"
            operator: "In"
            values:
            - "dani"
            - "raj"       # Aap ek se zyada values de sakte hain (OR condition)
          - key: "disktype"
            operator: "Exists" # Isme values dene ki zaroorat nahi padti