apiVersion: v1
kind: Pod
metadata:
  name: nodeselectorpod2
spec:
  containers:
  - name: nginx
    image: nginx:latest
  nodeSelector:
    mukesh: dani

# kubectl labels node <node_name> mukesh=dani (Create a label on the node)
# kubectl labels node <node_name> mukesh- (Remove a label from the node)
