apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
  labels:
    name: axion-ui
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80