FROM ubuntu:latest

LABEL org.opencontainers.image.description="This is my awesome frontend application built with Nginx"
LABEL org.opencontainers.image.authors="mukeshdani"
LABEL version="1.0"

RUN apt-get update && apt-get install -y nginx && apt-get clean

COPY index.html /var/www/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
