apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: digitalopsdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:          
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"