apiVersion: v1
kind: Pod
metadata: 
  name: bhakua-pod
  managedFields:
  - manager: "kubectl-create"
    operation: "Update"
    apiVersion: "v1"
  labels:
    app: bhakua
  annotations:
    description: "This is a sample pod definition for Bhakua application."
spec: