apiVersion: v1
kind: Pod
metadata: 
  name: bhakua-pod
  labels:
    app: bhakua
  annotations:
    description: "This is a sample pod definition for Bhakua application."
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  - name: firefox-container
    image: jlesage/firefox