apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_metadata_name }}
  labels:
    app: {{ .Values.metadata_label }}
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{ .Values.metadata_label }}
