apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
  namespace: digitalopsdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: telemetry
          image: aksdigitalopsregistry.azurecr.io/telemetry:v1
          ports:
            - containerPort: 8080
