apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: digitalopsdev
spec:
  type: LoadBalancer   
  selector:
    app: telemetry 
  ports:
    - protocol: TCP
      port: 8080            
      targetPort: 8080      
