apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-env     # Ye Role sirf is namespace mein chalega
  name: pod-manager-role
rules:
- apiGroups: [""]        # "" ka matlab 'core' group hota hai jisme Pods/Services aate hain. (Deployments ke liye "apps" likhna padta hai)
  resources: ["pods"]    # Kis resource par power deni hai
  verbs: ["get", "list", "watch", "create"] # Delete ki power NAHI di hai