apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: digitalopsdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: aksdigitalopsregistry.azurecr.io/ingestion:v1
          ports:
            - containerPort: 8080
