apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: digitalopsdev
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80                              
      targetPort: 80                       
