apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-simulator-service
  namespace: mkdspace
  labels:
    app: data-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-simulator
  template:
    metadata:
      labels:
        app: data-simulator
    spec:
      containers:
      - name: data-simulator
        image: axionacr2.azurecr.io/data-simulator-service:v2
        ports:
        - containerPort: 8000
